project:
  type: website

website:
  title: "earthquake-report"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - report.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

